version: "2"

services:
  node:
    image: "node:12"
    user: "node"
    container_name: node
    working_dir: /home/node/app
    environment:
      - PORT=8080
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - 8080:8080
    depends_on:
      - mariadb
    command: "npm run dev"

  mariadb:
    image: "mariadb"
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: xUnsbUoGSku7BmPZ1g2pTexA
      MYSQL_DATABASE: df_technical_test
      MYSQL_USER: user_rw
      MYSQL_PASSWORD: 1!dzM77%k